### ISSUE TITLE
Installation guide for macos

### ISSUE THREAD

**Issue by gmuc** [zfletch/apkg-to-csv#2]
test.sh not working on my mac:

$ ./test/test.sh
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- zip (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bin/apkg_to_csv.rb:4:in `<main>'
Tests failed: Files not equal

My ruby version is
$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

my osx: 10.13.6

Thank you!

**Comment by gmuc** [comment]
Solution install rubyzip: 

$ sudo gem install rubyzip

**Comment by gmuc** [comment]
Please add this in installation notes! Thanks!

**Comment by zfletch** [comment]
@gmuc thank you for reporting the issue!

The `rubyzip` requirement is specified in the `Gemfile` file, which is often how dependencies are tracked in Ruby projects. However, since there may be users not familiar with the Ruby ecosystem who are interested in converting their `.apkg` files, I have updated `README.md` with more detailed instructions.

Please feel free to take a look to see if it makes sense and/or suggest an update.
